name: Generate PDF
on: push

jobs:
  run:
    name: Generate PDF
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 16

      - name: Install resume-cli
        run: npm install -g resume-cli

      - name: Generate PDF
        run: resume export resume.pdf --theme actual

      - name: Commit changes
        uses: EndBug/add-and-commit@v9
        with:
          author_name: Phil Bell
          author_email: philhabell@gmailcom
          message: 'Updating PDF'
