name: Generate PDF
on: push

jobs:
  run:
    name: Generate PDF
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 16

      - name: Install dependancies
        run: npm install

      - name: Generate PDF
        run: npm run generate

      - name: Commit changes
        uses: EndBug/add-and-commit@v9
        with:
          default_author: github_actions
